<?php

/**
 * BaseCars
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $brand
 * @property string $model
 * @property string $submodel
 * @property timestamp $year
 * 
 * @method string    getBrand()    Returns the current record's "brand" value
 * @method string    getModel()    Returns the current record's "model" value
 * @method string    getSubmodel() Returns the current record's "submodel" value
 * @method timestamp getYear()     Returns the current record's "year" value
 * @method Cars      setBrand()    Sets the current record's "brand" value
 * @method Cars      setModel()    Sets the current record's "model" value
 * @method Cars      setSubmodel() Sets the current record's "submodel" value
 * @method Cars      setYear()     Sets the current record's "year" value
 * 
 * @package    SENS
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCars extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cars');
        $this->hasColumn('brand', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('model', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('submodel', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('year', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}