<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/11/08 03:12:01

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=SENS',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
