<?php

/**
 * CarsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CarsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CarsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cars');
    }
}