<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/11/07 02:09:14

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=SENS',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
